# Site settings
title: Bonaval
description: "Bonaval"
baseurl: "/Bonaval" 
url: "http://jatinderapex.github.io/Bonaval" 
tagline: "Apexure Software Solutions"

# Build settings
markdown: kramdown

highlighter: rouge
